export const chatList = [
  {
    userId: 1,
    userName: "Rishard vilson",
    userAvatar: "https://i.pravatar.cc/300",
    lastMessage: "how are you ?",
    lastMessageTime: "2 min",
    messageUnRead: 20,
    userActive: false,
  },
  {
    userId: 2,
    userName: "Roby son",
    userAvatar: "https://i.pravatar.cc/300",
    lastMessage: "hi",
    lastMessageTime: "2 hours",
    messageUnRead: null,
    userActive: false,
  },
  {
    userId: 3,
    userName: "Rishard vilson",
    userAvatar: "https://i.pravatar.cc/300",
    lastMessage: "okay",
    lastMessageTime: "",
    messageUnRead: null,
    userActive: true,
  },
  {
    userId: 4,
    userName: "Max Well",
    userAvatar: "https://i.pravatar.cc/300",
    lastMessage: "how are you ?",
    lastMessageTime: "2 min",
    messageUnRead: 20,
    userActive: false,
  },
  {
    userId: 5,
    userName: "Rishard vilson",
    userAvatar: "https://i.pravatar.cc/300",
    lastMessage: "how are you ?",
    lastMessageTime: "2 min",
    messageUnRead: 20,
    userActive: false,
  },
  {
    userId: 6,
    userName: "Marry",
    userAvatar: "https://i.pravatar.cc/300",
    lastMessage: "good night",
    lastMessageTime: "",
    messageUnRead: 20,
  },
  {
    userId: 4,
    userName: "Max Well",
    userAvatar: "https://i.pravatar.cc/300",
    lastMessage: "how are you ?",
    lastMessageTime: "2 min",
    messageUnRead: 20,
    userActive: false,
  },
  {
    userId: 5,
    userName: "Rishard vilson",
    userAvatar: "https://i.pravatar.cc/300",
    lastMessage: "how are you ?",
    lastMessageTime: "2 min",
    messageUnRead: 20,
    userActive: false,
  },
  {
    userId: 6,
    userName: "Marry",
    userAvatar: "https://i.pravatar.cc/300",
    lastMessage: "good night",
    lastMessageTime: "",
    messageUnRead: 20,
  },
];
